### ISSUE TITLE
Tried importing 2040b0 Demon's Souls flver, got "internal error setting the array"

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#70] opened 2024-09-28 00:44 UTC
Tried importing the 2040b0 flver from the m08_00_00_00 map in Demon's Souls and got this error:

![Screenshot 2024-09-27 194147](https://github.com/user-attachments/assets/0ba99f54-46e1-4195-9de6-53e44e227cf5)

I was able to import all of Boletaria using the msb import function, so this seems specific to some flvers. I tried importing 3-4 other flvers from the m08 tutorial map, and only 1 of them succeeded. the rest all had the same array error.

**Comment by Grimrukh** [comment] 2024-09-28 01:07
Gotcha, must be something funny with those materials, probably UV data. Will investigate.

**Comment by fromsoftserve** [comment] 2024-09-28 01:10
thank you so much! also I noticed when you export the flvers, it defaults to exporting them as flver.dcx, but weirdly Demon's Souls has both the .flver and the .flver.dcx. I've tested to make sure, and only modifying the .flver ones actually presents changed in game. Not sure why they doubled up like this.

**Comment by Grimrukh** [comment] 2024-09-28 03:35
Right; my guess is that the original disc had DCX files only, but the PS3 automatically unpacked them for usage, so that's the disc image we have today.

Re: the original problem, it seems to be specifically caused by my mesh-merging algorithm for these few map pieces. If you disable "Merge Submesh Vertices" on FLVER import, you can get around it for now.

**Comment by fromsoftserve** [comment] 2024-09-28 04:08
ahhh that makes sense.

and sounds good, thanks again!

**Comment by Grimrukh** [comment] 2024-09-29 22:52
This should be fixed in v2.1.3!

**Closed by Grimrukh** 2024-09-29 22:52 UTC
