### ISSUE TITLE
editing m2300b1A15 at all destroys it in game

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#25] opened 2023-12-06 15:47 UTC
in anor londo, there's a mesh hole I'm trying to fix, but anytime I fix it and export it. the mesh disappears in game, and in dsmapstudio it looks like the mesh exploded. only had this happen on one mesh in darkroot garden, but can't remember which one. probably QLOC flver shenanigans
![meshmessedup](https://github.com/Grimrukh/soulstruct-blender/assets/138341320/545e6aa0-bd3d-4ba9-8a23-2f2549329fbc)

**Comment by Grimrukh** [comment] 2023-12-19 07:06
Definitely a doozy - looks like there's something wrong with my mesh splitter that's only rearing its head in a few cases. Investigating!

**Comment by Grimrukh** [comment] 2023-12-22 06:32
This is fixed in v1.3.4. (It was caused by an incorrect vertex byte size for faces in very large meshes.)

**Closed by Grimrukh** 2023-12-22 06:32 UTC

**Comment by fromsoftserve** [comment] 2023-12-25 01:01
tysm! <3
