### ISSUE TITLE
FLVER Exporting: Mirrored UVs cause normal map artifacts

### ISSUE THREAD

**Issue by Xenthalos** [Grimrukh/soulstruct-blender#55] opened 2024-08-09 21:59 UTC
This is especially an issue on player skin, but in theory affects all mesh imports with any mirrored UVs (so, gloves that are symmetrical and use the same UV space for example).
If you want to see what I'm talking about, reimport BD_M_0000.flver and look at the difference in the player's back compared to vanilla. The right side's detail is not accurate, and there's a visible seam down the middle. You can also see there's a line going down the left arm.
It's pretty minor all things considered, and I don't have the technical knowledge to suggest how to fix it, but I'd be grateful if you could look into it!

(In my example, the left is vanilla, and the right is modded. I also made the left shoulder a bit bigger to make it obvious that it's a reimport.)
![image](https://github.com/user-attachments/assets/646b23da-5d08-47fb-8336-f004f0592cc9)

**Comment by Grimrukh** [comment] 2024-08-21 22:15
Looking into this!

**Comment by Grimrukh** [comment] 2024-08-22 06:39
This was being caused by vertex tangents requiring negation for faces with mirrored UVs. Fixed for the next update (which is a giant one), will leave this open until then.

**Comment by Xenthalos** [comment] 2024-08-22 21:56
Wow nice! That was really fast! Can't wait for the update. I wonder how noticeable the issue was on custom meshes before.

**Comment by Grimrukh** [comment] 2024-09-05 06:50
Soulstruct 2.0 is now released with this fix.

**Closed by Grimrukh** 2024-09-05 06:50 UTC
